# General site settings
title: Jules Perret
description: Personal page
lsi: false
safe: true
source: jperret21
incremental: false
highlighter: rouge
gist:
  noscript: false

# Markdown settings
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  markdown: kramdown

# Navigation links
header_pages:
  - about.md
  - research.md
  - bayesian_inference.md
  - publications.md
  - blog.md

# Collections and outputs
collections:
  posts:
    output: true

# Theme configuration
theme: minima
